name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      downloadURL:
        description: Velocity download URL
        required: true
        type: string
      tags:
        description: docker/metadata-action tags definition
        required: true
        type: string
        default: latest

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Download velocity jar
        run: wget -P velocity/ ${{ inputs.downloadURL }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: treysu/velocity
          tags: ${{ inputs.tags }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Summarize tags
        run: |
          echo "## Image tags" >> $GITHUB_STEP_SUMMARY
          while IFS= read -r line ;
            do echo "- $line" >> $GITHUB_STEP_SUMMARY;
          done <<< "$tags"
        env:
          tags: ${{ steps.docker_meta.outputs.tags }}
