name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      downloadURL:
        description: Velocity download URL
        required: true
        type: string
      tags:
        description: docker/metadata-action tags definition
        required: true
        type: string
        default: latest

jobs:
  docker-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download velocity jar
        run: wget -P velocity/ ${{ inputs.downloadURL }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: dockcenter/velocity
          tags: ${{ inputs.tags }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Summarize tags
        run: |
          echo "## Image tags" >> $GITHUB_STEP_SUMMARY
          while IFS= read -r line ;
            do echo "- $line" >> $GITHUB_STEP_SUMMARY;
          done <<< "$tags"
        env:
          tags: ${{ steps.docker_meta.outputs.tags }}
