on:
  push: {}
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

name: Watch velocity release

jobs:
  watch-releases:
    name: Watch velocity release
    runs-on: ubuntu-latest
    env:
      DRY_RUN: ${{ github.ref_name != 'main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Setup go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.23.2'
          check-latest: true
          cache: true
      - name: Run discover script
        run: go run github.com/treysu/velocity/cmd/discover
      - name: Dispatch 'Build and push Docker image' workflow
        run: scripts/dispatch.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
